# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml

# Build a Docker image with CI/CD and push to the GitLab registry.
# Docker-in-Docker documentation: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
#
# This template uses one generic job with conditional builds
# for the default branch and all other (MR) branches.
# only trigger on Push and schedule
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "$CI_DEFAULT_BRANCH"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - remote-check.sh
    - if: $CI_PIPELINE_SOURCE == "push"
      # always run on CI/CD changes, reagrdless if the packages are out-of-date or not
      changes:
        - .gitlab-ci.yml
      variables:
        quetre_out_of_date: "true"
        scribe_out_of_date: "true"
    - if: $CI_PIPELINE_SOURCE == "push"
      # update on Dockerfile or reagrdless if the package is out-of-date or not
      changes:
        - Dockerfile-quetre
      variables:
        quetre_out_of_date: "true"
    - if: $CI_PIPELINE_SOURCE == "push"
      # update on Dockerfile or reagrdless if the package is out-of-date or not
      changes:
        - Dockerfile-scribe
      variables:
        scribe_out_of_date: "true"
    # Allow run using the Run pipeline button
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_TITLE =~ /skip-ci$/
      when: never

stages:
  - check-for-updates
  - build-quetre
  - build-scribe

fetch-commit-hash:
  image: alpine:latest
  stage: check-for-updates
  # don't run when variables are already set.
  before_script:
    - |
      if [ "$quetre_out_of_date" = true ]; then
        echo "Variable already set, won't run checks" && exit 0
      else
        echo "Variable isn't set, continue with checks"
      fi
  script:
    - apk add git
    - sh remote-check.sh https://github.com/zyachel/quetre quetre-local.txt build-hashes/quetre.txt quetre_out_of_date
    - sh remote-check.sh https://git.sr.ht/~edwardloveall/scribe scribe-local.txt build-hashes/scribe.txt scribe_out_of_date
    - cat check.env
  # pass environment variable file to other dependent jobs, https://docs.gitlab.com/ee/ci/variables/#pass-an-environment-variable-to-another-job
  artifacts:
    reports:
      dotenv: check.env

quetre-buildx:
  image: jdrouet/docker-with-buildx:stable
  needs:
    - fetch-commit-hash
  services:
    - docker:dind
  stage: build-quetre
  variables:
    CONTEXT: .
    IMAGE_NAME: fariszr/quetre
    CACHE_IMAGE: fariszr/privacy-oci/quetre-cache
    DOCKER_FILE: Dockerfile-quetre
  before_script:
    # workaround for https://gitlab.com/gitlab-org/gitlab/-/issues/235812, you can't use Shell variables in rules.
    - |
      if [ "$quetre_out_of_date" = true ]; then
        echo "true, needs update"
      else
        echo "false, no need for update, no build needed" && exit 0
      fi
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" docker.io
  script:
    - docker buildx create --use
    - docker buildx build --push --pull -t docker.io/$IMAGE_NAME:latest --cache-from $CI_REGISTRY/$CACHE_IMAGE:latest --cache-to $CI_REGISTRY/$CACHE_IMAGE:latest --file $DOCKER_FILE --platform linux/amd64,linux/arm64,linux/arm/v7 .

quetre-update-build-hash:
  image: alpine:latest
  needs:
    - fetch-commit-hash
    - quetre-buildx
  stage: build-quetre
  variables:
    HASH_FILE: build-hashes/quetre.txt
    APP_NAME: quetre
    REPO: https://github.com/zyachel/quetre
  before_script:
    # workaround for https://gitlab.com/gitlab-org/gitlab/-/issues/235812, you can't use Shell variables in rules.
    - |
      if [ "$quetre_out_of_date" = true ]; then
        echo "true, needs update"
      else
        echo "false, no need for update, no build needed" && exit 0
      fi
    - apk add git
    - git remote set-url origin https://${CI_REGISTRY_USER}:${API_TOKEN}@${CI_REPOSITORY_URL#*@}
    # Set the displayed user with the commits that are about to be made
    - git config --global user.email "${GIT_USER_EMAIL:-$GITLAB_USER_EMAIL}"
    - git config --global user.name "${GIT_USER_NAME:-$GITLAB_USER_NAME}"
  script:
    - git ls-remote $REPO HEAD > $HASH_FILE
    - git checkout main
    - git pull
    - git add $HASH_FILE
    - git diff-index --quiet HEAD || git commit -m "[skip-ci] update $APP_NAME build commit" # avoid error when there are no changes https://stackoverflow.com/a/8123841
    - git push

scribe-build-kaniko:
  # use kainkio, since its a lot faster and scribe only works on AMD64.
  stage: build-scribe
  needs:
    - fetch-commit-hash
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    REPO: git://git.sr.ht/~edwardloveall/scribe
    HASH_FILE: build-hashes/scribe.txt
    APP_NAME: scribe
    IMAGE_NAME: fariszr/scribe
    DOCKER_FILE: Dockerfile-scribe
  before_script:
    # workaround for https://gitlab.com/gitlab-org/gitlab/-/issues/235812, you can't use Shell variables in rules.
    - |
      if [ "$scribe_out_of_date" = true ]; then
        echo "true, needs update"
      else
        echo "false, no need for update, no build needed" && exit 0
      fi
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" "${DOCKER_USER}" "${DOCKER_PASS}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context "$REPO" --dockerfile "$CI_PROJECT_DIR/$DOCKER_FILE" --destination "docker.io/$IMAGE_NAME:latest"

scribe-update-build-hash:
  image: alpine:latest
  needs:
    - fetch-commit-hash
    - scribe-build-kaniko
  stage: build-scribe
  variables:
    REPO: https://git.sr.ht/~edwardloveall/scribe
    HASH_FILE: build-hashes/scribe.txt
    APP_NAME: scribe
    IMAGE_NAME: fariszr/privacy-oci/scribe
    CACHE_IMAGE: fariszr/privacy-oci/scribe-cache
    DOCKER_FILE: Dockerfile-scribe
  before_script:
    # workaround for https://gitlab.com/gitlab-org/gitlab/-/issues/235812, you can't use Shell variables in rules.
    - |
      if [ "$scribe_out_of_date" = true ]; then
        echo "true, needs update"
      else
        echo "false, no need for update, no build needed" && exit 0
      fi
    - apk add git
    # use user access token with only repo write access to push, https://devops.stackexchange.com/a/14240
    - git remote set-url origin https://${CI_REGISTRY_USER}:${API_TOKEN}@${CI_REPOSITORY_URL#*@}
    # Set the displayed user with the commits that are about to be made
    - git config --global user.email "${GIT_USER_EMAIL:-$GITLAB_USER_EMAIL}"
    - git config --global user.name "${GIT_USER_NAME:-$GITLAB_USER_NAME}"
  script:
    - git ls-remote $REPO HEAD > $HASH_FILE
    - git checkout main
    - git pull
    - git add $HASH_FILE
    - git diff-index --quiet HEAD || git commit -m "[skip-ci] update $APP_NAME build commit" # avoid error when there are no changes https://stackoverflow.com/a/8123841
    - git push