FROM node:14-alpine as build
RUN apk --no-cache add git python3 make g++
WORKDIR /app
RUN git clone https://git.sr.ht/~cadence/bibliogram /app
RUN mv ./.config.js.default ./config.js
RUN npm install --no-optional

FROM node:14-alpine as app
WORKDIR /app
COPY --from=build /app /app
RUN apk add --no-cache graphicsmagick
EXPOSE 10407
CMD ["npm", "start"]

# labels according to https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL org.opencontainers.image.url https://gitlab.com/FarisZR/Privacy-OCI
LABEL org.opencontainers.image.licenses AGPL-3.0
LABEL org.opencontainers.image.title Scribe
LABEL org.opencontainers.image.description "Auto updated Container for Scribe, A privacy proxy for Medium.com and Github gists"