FROM node:14.5.0-alpine as build
RUN apk --no-cache add git python3 make g++
WORKDIR /app
RUN git clone https://git.sr.ht/~cadence/bibliogram /app
RUN mv ./.config.js.default ./config.js
RUN npm install --no-optional

FROM node:14.5.0-alpine as app
WORKDIR /app
COPY --from=build /app /app
RUN apk add --no-cache graphicsmagick
EXPOSE 10407
CMD ["npm", "start"]