services:
  srcibe:
    container_name: scribe
    image: oci.fariszr.com/fariszr/quetre:latest
    restart: always
    ports:
      - 127.0.0.1:8080:8080 #remember to always use a reverse proxy!
    environment:
      - APP_DOMAIN=scribe.example.com
      - LUCKY_ENV=production
      - PORT=8080 #SCRIBE_PORT doesn't do anything
      - SECRET_KEY_BASE=xxxx # lucky gen.secret_key
      - GITHUB_USERNAME=xxx # optional, only if you want to proxy gists
      - GITHUB_PERSONAL_ACCESS_TOKEN=xxx # optional, only if you want to proxy gists

  quetre:
    image: oci.fariszr.com/fariszr/quetre:latest
    container_name: quetre
    restart: always
    ports:
      - 127.0.0.1:3000:3000 #remember to always use a reverse proxy!
    # volumes:
    #  - ./quetre/.env:/app/.env:ro #optional

  breezewiki:
    container_name: breezewiki
    image: oci.fariszr.com/fariszr/breezewiki:latest
    restart: always
    environment:
      - bw_canonical_origin=breezewiki.example.com
      - bw_feature_search_suggestions=true
      - bw_port=8000

  simplytranslate:
    container_name: simplytranslate
    image: oci.fariszr.com/fariszr/simplytranslate:latest
    restart: always
    environment:
      - ADDRESS=0.0.0.0:5000
      - GOOGLETRANSLATE_ENABLE=true
      - ICIBA_ENABLE=true
      - REVERSO_ENABLE=true

  # Deprecated
  bibliogram:
    image: fariszr/bibliogram:latest
    container_name: bibliogram
    restart: always
    ports:
      - 127.0.0.1:10407:10407 #remember to always use a reverse proxy!
    volumes:
      - ./bibliogram/config.js:/config/config.js:ro